version: 2

updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
      time: '04:00'
      timezone: America/New_York
    commit-message:
      prefix: '[skip netlify] '

  - package-ecosystem: npm
    directory: '/'
    versioning-strategy: increase
    schedule:
      interval: weekly
      time: '04:00'
      timezone: America/New_York
    commit-message:
      prefix: '[skip netlify] '
    groups:
      npm-major-upgrades:
        update-types:
          - 'major'
      npm-minor-upgrades:
        update-types:
          - 'minor'
          - 'patch'
    ignore:
      - dependency-name: 'date-fns'
        versions:
          - 3.x
