compressionLevel: mixed
enableGlobalCache: false
nodeLinker: node-modules

packageExtensions:
  markdown-it-anchor@*:
    peerDependenciesMeta:
      "@types/markdown-it":
        optional: true
  stylelint-config-recommended-scss@*:
    dependencies:
      postcss: "*"
