nodeLinker: node-modules

packageExtensions:
  markdown-it-anchor@*:
    peerDependenciesMeta:
      "@types/markdown-it":
        optional: true
  stylelint-config-recommended-scss@*:
    dependencies:
      postcss: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.3.1.cjs
