plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

packageExtensions:
  "markdown-it-anchor@*":
    peerDependenciesMeta:
      "@types/markdown-it":
        optional: true
  "stylelint-config-recommended-scss@*":
    dependencies:
      postcss: "*"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
