packageExtensions:
  markdown-it-anchor@*:
    peerDependenciesMeta:
      "@types/markdown-it":
        optional: true
  stylelint-config-recommended-scss@*:
    dependencies:
      postcss: "*"
  # Fix for: https://github.com/facebook/jest/issues/13332
  jest-runner@*:
    dependencies:
      exit: '*'
  jest-worker@*:
    dependencies:
      jest-util: '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.3.cjs
