[build.environment]
    NODE_VERSION = "16"
    YARN_VERSION = "3.2.4"

[[plugins]]
    package = "netlify-plugin-11ty"

    [plugins.inputs]
        cache_img = "./assets/images"
        cache_assets = false

[[plugins]]
    package = "@netlify/plugin-a11y"

    [plugins.inputs]
        checkPaths = [
          "/index.html",
          "/work/index.html",
          "/services/index.html",
          "/tools/index.html",
          "/blog/index.html",
          "/about/index.html",
          "/contact/index.html",
        ]
        failWithIssues = false

[[plugins]]
    package = "@algolia/netlify-plugin-crawler"

    [plugins.inputs]
        branches = ["main"]
        mainBranch = "main"
        template = "hierarchical"

[[redirects]]
    from = "/herman/docs/*"
    to = "https://herman-docs.netlify.app/herman/docs/:splat"
    status = 200
