[build.environment]
    NODE_VERSION = "18"
    YARN_VERSION = "4.1.0"
    YARN_CACHE_FOLDER = "/opt/buildhome/.yarn_cache"

[[plugins]]
    package = "netlify-plugin-11ty"

    [plugins.inputs]
        cache_img = "./assets/images"
        cache_assets = false

[[plugins]]
    package = "@netlify/plugin-a11y"

    [plugins.inputs]
        checkPaths = [
          "/index.html",
          "/work/index.html",
          "/services/index.html",
          "/tools/index.html",
          "/blog/index.html",
          "/about/index.html",
          "/contact/index.html",
        ]
        ignoreElements = '#search'
        ignoreGuidelines = ['color-contrast']
        failWithIssues = true

[[plugins]]
    package = "@algolia/netlify-plugin-crawler"

    [plugins.inputs]
        branches = ["main"]
        mainBranch = "main"
        template = "hierarchical"

[[redirects]]
    from = "/accoutrement/docs/*"
    to = "https://accoutrement-docs.netlify.app/accoutrement/docs/:splat"
    status = 200

[[redirects]]
    from = "/blend/docs/*"
    to = "https://blend-docs.netlify.app/blend/docs/:splat"
    status = 200

[[redirects]]
    from = "/cascading-colors/docs/*"
    to = "https://cascading-colors-docs.netlify.app/cascading-colors/docs/:splat"
    status = 200

[[redirects]]
    from = "/herman/docs/*"
    to = "https://herman-docs.netlify.app/herman/docs/:splat"
    status = 200

[[redirects]]
    from = "/susy/docs/*"
    to = "https://susy-docs.netlify.app/susy/docs/:splat"
    status = 200

[[redirects]]
    from = "/true/docs/*"
    to = "https://true-docs.netlify.app/true/docs/:splat"
    status = 200
