[build.environment]
   NODE_VERSION = "18"
   YARN_VERSION = "3.2.4"

[[plugins]]
    package = "netlify-plugin-11ty"

    [plugins.inputs]
        cache_img = false
        cache_assets = false

[[plugins]]
    package = "@netlify/plugin-a11y"

[[plugins]]
    package = "@algolia/netlify-plugin-crawler"

    [plugins.inputs]
        branches = ["main"]
        mainBranch = "main"
        template = "hierarchical"
