domain: www.oddbird.net
url: https://www.oddbird.net/
title: OddBird
description: |
  Scalable, accessible, and performant web applications
  with a human-centered design.
email: birds@oddbird.net
images: ./src/images/
feed: /feed.atom
styles:
  - screen.css
facebook_id: 1820980378150914
google_analytics_id: UA-36510846-1
social:
  email: birds
  twitter: oddbird
  github: oddbird
nav:
  - url: /work/
  - url: /services/
  - url: /tools/
  - url: /blog/
  - url: /about/
  - url: /contact/
me:
  - https://www.oddbird.net/
  - mailto:birds@oddbird.net
  - https://twitter.com/oddbird
  - https://github.com/oddbird
