domain: www.oddbird.net
url: https://www.oddbird.net/
title: OddBird
description: |
  Scalable, accessible, and performant web applications
  with a human-centered design.
email: birds@oddbird.net
images: ./src/images/
feed: /feed.atom
styles:
  - screen.css
facebook_id: 1820980378150914
social:
  - email: birds
  - mastodon:
      user: oddbird
      server: front-end.social
  - github: oddbird
nav:
  - url: /work/
  - url: /services/
  - url: /tools/
  - url: /talks/
    title: Talks
  - url: /blog/
  - url: /about/
  - url: /contact/
me:
  - https://www.oddbird.net/
  - mailto:birds@oddbird.net
  - https://front-end.social/@OddBird
  - https://github.com/oddbird
