url: https://www.oddbird.net/
title: OddBird
description: |
  Scalable, accessible, and performant web applications
  with a human-centered design.
email: birds@oddbird.net
images: /assets/images/
feed: /feed.atom
styles:
  - screen.css
facebook_id: 1820980378150914
google_analytics_id: UA-36510846-1
social:
  email: birds
  twitter: oddbird
nav:
  - url: /work/
  - url: /services/
  - url: /open-source/
  - url: /blog/
  - url: /birds/
  - url: /jobs/
  - url: /contact/
