name: Winging It 2.0
description: Issue form template for Winging It Episodes
title: "Winging It - "
projects: ["oddbird/7", "oddbird/13"]
body:
  - type: markdown
    attributes:
      value: "*Include the episode number and topic in the issue title*"
  - type: checkboxes
    id: expert
    attributes:
      label: Who is the expert?
      options:
      - label: David
      - label: Ed
      - label: James
      - label: Jonny
      - label: Miriam
      - label: Sondra
      - label: Stacy
      - label: Other (for Guests, add name to Episode Description)
  - type: checkboxes
    id: cohosts
    attributes:
      label: Who are the co-hosts?
      description: "Select all that apply"
      options:
      - label: David.
      - label: Ed.
      - label: James.
      - label: Jonny.
      - label: Miriam.
      - label: Sondra.
      - label: Stacy.
      - label: Other.
  - type: input
    id: notes
    attributes:
      label: Show Notes Link
      description: "[Show Notes Template](https://docs.google.com/document/d/1Sp_-JSzoFoqq8IdTqaQl6oNSEbWlxNfuqZ6fKE14ELQ/edit?usp=sharing)"
  - type: input
    id: date
    attributes:
      label: Recording Date
  - type: markdown
    attributes:
      value: "## After Recording"
  - type: input
    id: streamyardlink
    attributes:
      label: Video File Link (Streamyard)
  - type: input
    id: youtubelink
    attributes:
      label: YouTube Link
  - type: input
    id: oddsitelink
    attributes:
      label: OddSite Link
  - type: textarea
    id: episodetitle
    attributes:
      label: Title Suggestions for Episode
      description: "Will be used on YouTube and OddSite"
  - type: textarea
    id: episodedesc
    attributes:
      label: Episode Description for YouTube (and OddSite) Post
      description: "Will be used on YouTube and OddSite"
  - type: textarea
    id: chapters
    attributes:
      label: Chapters
      description: "Include a 4 digit timestamp & short chapter title per line"
      value: |
        00:01 Chapter Name
  - type: textarea
    id: production
    attributes:
      label: Production Checklist
      value: |
        - [ ] [Create Video thumbnail](https://www.dropbox.com/scl/fi/46qduwbgrq1z294yaoad3/winging-it-thumbnail-template.psd?rlkey=7i5yf7uw4o3960nk0kt4c80bq&dl=0) for YouTube
        - [ ] [Create OddSite Hero image](https://www.dropbox.com/home/OddBird/oddbird%20%3A%20oss%20projects/winging%20it/thumbnails)
        - [ ] Create OddSite Post
        - [ ] Edit Video
        - [ ] Upload Video to YT and add unlisted video link to this issue
        - [ ] Review Video
        - [ ] Make OddSite Post
        - [ ] Review OddSite Post PR
        - [ ] Publish video/ Publish PR (at the same time)
        - [ ] Promote video (on all the socials)
        - [ ] Add to Playlist (if applicable)
