name: Winging It 2.0
description: Issue template for tracking Winging It Episodes
title: "Winging It 2 - "
projects: ["oddbird/7", "oddbird/13"]
body:
  - type: markdown
    attributes:
      value: "*Include the episode number and topic in the issue title*"
  - type: dropdown
    id: expert
    attributes:
      label: Who is the expert?
      options:
        - David
        - Ed
        - James
        - Jonny
        - Miriam
        - Sondra
        - Stacy
    validations:
      required: false
  - type: dropdown
    id: cohosts
    attributes:
      label: Who are the co-hosts (select all that apply)
      multiple: true
      options:
        - David
        - Ed
        - James
        - Jonny
        - Miriam
        - Sondra
        - Stacy
    validations:
      required: false
  - type: input
    id: notes
    attributes:
      label: Show Notes Link
    validations:
      required: false
  - type: input
    id: date
    attributes:
      label: Recording Date
    validations:
      required: false
  - type: markdown
    attributes:
      value: "## After Recording"
  - type: input
    id: streamyardlink
    attributes:
      label: Video File Link (Streamyard)
    validations:
      required: false
  - type: input
    id: youtubelink
    attributes:
      label: YouTube Link
    validations:
      required: false
  - type: input
    id: oddsitelink
    attributes:
      label: OddSite Link
    validations:
      required: false
  - type: textarea
    id: episodetitle
    attributes:
      label: Title Suggestions for Episode
      description: "Will be used on YouTube and OddSite"
    validations:
      required: false
  - type: textarea
    id: episodedesc
    attributes:
      label: Episode Description for YouTube (and OddSite) Post
      description: "Will be used on YouTube and OddSite"
    validations:
      required: false
  - type: textarea
    id: chapters
    attributes:
      label: Chapters
      description: "Include a 4 digit timestamp & short chapter title per line"
      value: |
        00:01 Chapter Name
    validations:
      required: false
  - type: textarea
    id: production
    attributes:
      label: Production Checklist
      value: |
        - [ ] Create Video thumbnail for YouTube
        - [ ] Create OddSite Hero image
        - [ ] Create OddSite Post
        - [ ] Edit Video
        - [ ] Upload Video to YT and add unlisted video link to this issue
        - [ ] Review Video
        - [ ] Make OddSite Post
        - [ ] Review OddSite PR
        - [ ] Publish video
        - [ ] Promote video (on all the socials)
        - [ ] Review analytics
