name: Trigger Netlify Build

on:
  workflow_dispatch: # Allow running on-demand
  schedule:
    # Every day at 8:00 UTC (3:00 or 4:00 Eastern)
    - cron: '0 8 * * *'

jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: POST to Build Hook
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/${{ secrets.NETLIFY_BUILD_HOOK }}
