name: Sync branches with shadow repo

on:
  create:
  delete:
  pull_request:
    types: [opened]

env:
  API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
  SHADOW_OWNER: ${{ secrets.SHADOW_OWNER }}
  SHADOW_REPO: ${{ secrets.SHADOW_REPO }}

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    if: github.event.ref_type == 'branch'
    steps:
      - name: Clone shadow repo
        run: git clone --single-branch "https://$API_TOKEN_GITHUB@github.com/$SHADOW_OWNER/$SHADOW_REPO.git" .
      - name: Create branch on shadow repo
        if: github.event_name == 'create'
        run: git push origin main:${{ github.event.ref }}
      - name: Delete branch on shadow repo
        if: github.event_name == 'delete'
        run: git push origin --delete ${{ github.event.ref }}

  diff-link:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    steps:
      - name: Add link to diff
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.number }}
          body: |
            View diff of compiled files (may take a few minutes): https://github.com/${{ env.SHADOW_OWNER }}/${{ env.SHADOW_REPO }}/compare/${{ github.event.pull_request.base.ref }}..${{ github.event.pull_request.head.ref }}
